name: visualize_llm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - streamlit=1.46.1
  - matplotlib=3.10.3
  - pygraphviz=1.14
  - pip
  - pip:
      - transformer-lens==2.16.1
      - torch==2.7.1